name: Prevent direct main push (educational)

on:
  push:
    branches: [ main ]

jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if not GitHub Actions bot
        run: |
          if [ "${{ github.actor }}" != "github-actions[bot]" ]; then
            echo "Direct pushes to main are not allowed. Please use PRs." >&2
            exit 1
          fi
          echo "Push by GitHub Actions bot allowed."

